name: dev

on:
  push:
    branches:
    - develop

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - run: npm install
    - run: cd functions && npm install && cd ..
    - run: npm run prebuild
    - run: npm run build
    - uses: w9jds/firebase-action@master
      with:
        args: deploy -P dev
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
